# Generated by Django 4.0.6 on 2022-07-07 20:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/defaults/default-1.png', null=True, upload_to=accounts.models.upload_path),
        ),
    ]
