# Generated by Django 4.0.6 on 2022-07-07 21:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=accounts.models.random_avatar_image_url, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
