# Generated by Django 4.0.6 on 2022-07-08 14:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otprequest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[accounts.models.PhoneNumberValidator]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
