# Generated by Django 4.0.6 on 2022-07-09 13:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otprequest_email_otprequest_phone_user_is_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='refresh',
            field=models.DateTimeField(default=accounts.models.create_refresh_time),
        ),
    ]
