# Generated by Django 4.0.6 on 2022-07-09 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='register_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
