# Generated by Django 4.0.6 on 2022-07-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_replied',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_comment', to='blog.comment'),
        ),
    ]
