# Generated by Django 4.0.6 on 2022-07-10 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_comment_created_comment_editable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_replied',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_replied_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
